# Generated by Django 6.0 on 2026-01-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total order amount",
                max_digits=15,
                verbose_name="Total Amount",
            ),
        ),
    ]
