# Generated by Django 6.0 on 2026-01-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter a name for the item",
                        max_length=100,
                        verbose_name="Item Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Enter a description for the item",
                        verbose_name="Description",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter a price for the item",
                        max_digits=15,
                        verbose_name="Price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "US Dollar"), ("EUR", "Euro")],
                        default="USD",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="products_it_name_1ce201_idx"),
                    models.Index(fields=["price"], name="products_it_price_4e76b3_idx"),
                    models.Index(
                        fields=["currency"], name="products_it_currenc_4ba3a7_idx"
                    ),
                ],
            },
        ),
    ]
